{
  "name": "asics-scraper",
  "version": "1.0.0",
  "description": "ASICS B2B Weekly Batch Scraper with Self-Hosted Browserless",
  "main": "server.js",
  "scripts": {
    "start": "node server.js",
    "dev": "node server.js",
    "build": "echo 'No build needed for self-hosted setup'"
  },
  "dependencies": {
    "express": "4.18.2",
    "puppeteer-core": "21.6.1",
    "pg": "8.11.3",
    "node-cron": "3.0.3"
  },
  "engines": {
    "node": "20.x"
  }
}
