version: '3.8'

services:
  # Your ASICS scraper application
  asics-scraper:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    environment:
      # Application settings
      - NODE_ENV=production
      - PORT=10000
      
      # Database connection (from Railway variables)
      - DATABASE_URL=${DATABASE_URL}
      
      # ASICS B2B credentials (from Railway variables)
      - ASICS_USERNAME=${ASICS_USERNAME}
      - ASICS_PASSWORD=${ASICS_PASSWORD}
      
      # Browserless connection (internal container communication)
      - BROWSERLESS_ENDPOINT=ws://browserless:3000
      
      # Optional: Timezone
      - TZ=America/New_York
      
      # Optional: Logging level
      - LOG_LEVEL=info
    
    depends_on:
      - browserless
    
    restart: unless-stopped
    
    # Health check to ensure service is running
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits for Railway TRIAL
    deploy:
      resources:
        limits:
          memory: 450M  # Reduced for trial
          cpus: '0.8'
        reservations:
          memory: 200M
          cpus: '0.4'

  # Self-hosted Browserless container (TRIAL OPTIMIZED)
  browserless:
    image: ghcr.io/browserless/chromium:latest
    ports:
      - "3000:3000"
    environment:
      # Browser session limits (VERY conservative for trial)
      - MAX_CONCURRENT_SESSIONS=1  # Only 1 session at a time
      - MAX_QUEUE_LENGTH=5
      
      # Connection settings
      - CONNECTION_TIMEOUT=60000
      - DEFAULT_LAUNCH_ARGS=["--no-sandbox","--disable-setuid-sandbox","--disable-dev-shm-usage","--disable-gpu","--disable-background-timer-throttling","--disable-backgrounding-occluded-windows","--disable-renderer-backgrounding","--memory-pressure-off","--max_old_space_size=400"]
      
      # Performance settings (memory-optimized)
      - PREBOOT_CHROME=false  # Save memory on startup
      - ENABLE_CORS=true
      - MAX_MEMORY_PERCENT=80
      - KEEP_ALIVE=false  # Don't keep browsers alive to save memory
      
      # Security settings
      - ENABLE_DEBUG_VIEWER=false
      - ENABLE_HEAP_DUMP=false
      
      # Timezone
      - TZ=America/New_York
    
    restart: unless-stopped
    
    # Health check for Browserless
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/json/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Resource limits (TRIAL OPTIMIZED)
    deploy:
      resources:
        limits:
          memory: 450M  # Reduced from 1G
          cpus: '0.7'
        reservations:
          memory: 300M
          cpus: '0.3'
    
    # Minimal volumes for trial
    volumes:
      - browserless-cache:/tmp/.cache

# Named volumes for data persistence
volumes:
  browserless-cache:
    driver: local

# Network configuration
networks:
  default:
    driver: bridge
